---
title: "Ch02_01Basic"
author: "Anish Mohan"
date: "January 17, 2017"
output: html_document
---


```{r}
# Declaring a vector
 x <- c(1,2,3,4)

# Length of Vector
 length(x)

# Adding Vectors
 x = c(1,2,3)
 y = c(9,8,7)
 x+y
```

```{r}
# ls() function gives list of all the objects (data and functions)
 ls()
 
# Remove an objects
 rm(x)
 
# Remove all objects
 rm (list = ls())
```


```{r}
#Matrix Declaration
 x = matrix(data = c(1,2,3,4), nrow = 2, ncol = 2) #Note entries go in each row for the same column first
 x
 
# Another way
 y = matrix(c(4,5,6,7,8,9), 2,3)
 y
 
# Entering the entries by each column first (per row)
 z = matrix(data=c(1,2,3,4,5,6), 2, 2, byrow = TRUE)
 z
```

```{r}
# Some simple functions: Square Root
 x = matrix(c(4,9,16,25),2,2)
 sqrt(x)
 
# Squaring values
 x = matrix(c(1,2,3,4),2,2)
 x^2
```


Random Values

```{r}
x = rnorm(50) # Random 50 values, with mean of 0 and std dev = 1
plot(x)

y = rnorm(50, mean=5, sd = 0.1) #50 values with mean around 5 and std dev = 0.1
plot(y)
```

Graphics:

```{r}
x = rnorm(100)
y = rnorm(100)
plot(x,y, xlab = "X-axis",ylab = "y-axis", main="Plot of X vs Y")

```

Saving figures into different file types

```{r}
pdf("figure.pdf") # can be jpeg()
plot(x,y, col="green")
dev.off #Tells r that plot creation is done
```


Sequence
```{r}
x=1:10
x
x = seq(1,10)
x
x = seq(1,10,length = 10)
x
```


Contour plots
```{r}
x = seq(-pi,pi, length = 50)
y = x
f = outer(x,y, function(x,y) x^2+y^2) # outer product of the vectors  and use the function given as the next argument
contour(x,y,f)
f = outer(x,y, function(x,y) cos(x+y))
contour(x,y,f)
f = outer(x,y, function(x,y) cos(y)/(1+x^2)) # outer product of the vectors  and use the function given as the next argument
contour(x,y,f)
contour(x,y,f,nlevels = 45, add = T)
```

Image plots:
Image works same as contours but gives a heat map
```{r}
x = seq(-pi,pi, length = 50)
y = x
f = outer(x,y, function(x,y) x^2+y^2) # outer product of the vectors  and use the function given as the next argument
image(x,y,f)

persp(x,y,f, theta = 30, phi = 20) #Theta and Phi can be use to produce 3d using perspective function
  
```

Indexing Data

```{r}
A = matrix(1:16,4,4)
A
A[2,3]
A[c(1,3),c(1,3)]
A[1:3,1:3]
A[,2:4]


A[-c(1:3),] #-ve sign is used to indicate omission
A[c(1:3),] #compare with and without -ve sign
```

Reading and Working with tables
```{r}
Auto = read.table("Auto.data") #Read the text file from the working directory
fix(Auto)
# Dataset not loaded correctly because
# 1. R assumed variable names as part of data
# 2. Data has missing observations

# Fix the problems
Auto = read.table("Auto.data", header = TRUE, na.strings = "?") #Gives info about header and species that ? should be marked as NA

# First 5 rows of the data file
head(Auto)

# Dimension of the data file
dim(Auto)

# Dealing with missing data
  # is.na returns true if an entry is NA and false otherwise.
  # Doing a summary shows the number of NAs per column
  summary(is.na(Auto))

#There are 5 rows in horsepower column with missing data; for now we will omit these rows
Auto = na.omit(Auto)
dim(Auto) # Note number of rows have reduced.

#Names of the column
names(Auto)
```

Addtional Graphical and Numerical summary of the data: Plots
```{r}
# Use attach for a dataset where we are going to refer its column names
attach(Auto)
plot(cylinders,mpg) #Shows a simple plot

# cylinder variable is stored as numeric vector; it can be treated as a qualititative/categorical variable
plot(as.factor(cylinders), mpg) # if the variable plotted on x-axis is categorical, then box plots are produced.

#various plot variables
cylinders = as.factor(cylinders)
plot(cylinders,mpg)
plot(cylinders,mpg, col = "red")
plot(cylinders, mpg, col = "red", varwidth = T) # Varwidth: Boxes are drawn with widths proportional to square root of # of observations
plot(cylinders, mpg, col = "red", varwidth = T, horizontal = T, xlab = "Cylinder") #Horizontal layout
plot(cylinders, mpg, xlab ="Cylinders", ylab = "Miles per Gallon", main = "Cylinders vs MPG")
```

Histogram
```{r}
hist(mpg)
hist(mpg, col = 2) #col stands for color
hist(mpg, col = 2, breaks = 15) # Number of bins
hist(mpg, col = "green", breaks = 15) # Number of bins
```

Scatterplot matrix
```{r}
pairs(Auto)
pairs(~ mpg + horsepower + weight, Auto)
```

Using Identify function
```{r}
# Identify provides interactive method for identifying value of a particula variable for points on plot
# Arguments are x-axis, y-axis and the variable whose value you want to print
plot(horsepower, mpg)
identify(horsepower, mpg, weight)
```

Summary function
```{r}
# Summary provides numerical summary of quantitative data and for qualitative data (categorical data) it just produces number of entires for each category
summary(Auto)

```