---
title: "Ch02_ExerLabs"
author: "Anish Mohan"
date: "January 18, 2017"
output: html_document
---

# Question 8

```{r}
college = read.csv("College.csv", header = TRUE)

# Look at the data
head(college)

# First column is the name of the college; Do not want R to treat this as data. 
# Use this first column and enter them as "row.names" of the row. This implies that R has given each row a name corresponding to appropriate university
rownames(college) = college[,1]
head(college)

#Now remove the first column
college = college[,-1]
head(college)

# Check dimensions
dim(college)

# Check type of variables
str(college)

# Using summary to produce numerical summary of variables
summary(college)

# Using pairs to plot scatter plot of first 10 variables
pairs(college[,1:10])

# Using plot to produce boxplots of Outstate vs Private
attach(college)
plot(Private, Outstate, xlab = "Private", ylab = "Outstate", main = "Private vs Outstate")


# Create a new qualitative variable :- Elite by binning Top 10 percent (Top10perc variable)
# Plan: Divide universities into 2 groups based on wheth;er proportion of students coming from the top 10% of their high school exceeds 50%

 Elite = rep("No", nrow(college)) # Create a vector of "No" with number of rows = nrow of college
 Elite[Top10perc > 50] = "Yes" # Yes for a university that has more than 50% students who were in top 10 percentile of thier class
 
 Elite = as.factor(Elite) # Treat Elite as a categorical variable
 college = data.frame(college, Elite) #Merge the data frames
 
 # Summary of the new Column "Elite"
 summary(college$Elite)
 
 plot(Elite, Outstate, xlab = "Elite", ylab = "Outstate", main = "Elite vs Outstate")
```


Histograms

```{r}
par(mfrow = c(2,2))
hist(college$Apps, breaks = 15)
hist(college$Accept)
hist(college$Enroll, breaks = 15, xlab = "Enrollment", ylab = "Frequency", main = "Histrogam of Enrollment")
hist(college$Grad.Rate, breaks = 20)

```


# Question 9

```{r}
auto = read.table("Auto.data", header = TRUE)

#SUmmary of Auto
summary(auto)

# Checking if there are any is.na
summary(is.na(auto))

# Predictors that are qualitative or quantitative
str(auto)
# Predictors that are quantitative: mpg, Cylinders, displacement, weight, acceleration, year, origin.
# Predictors that are qualitative : horsepower, 

#Range of Quantitative 
quant = c("mpg","cylinders","displacement","weight","acceleration","year","origin")
for(c in quant){
  print(c)
  print(range(auto[[c]]))
}


#Mean and std deviation of each quantitative predictor
lapply(auto,mean)
lapply(auto,sd)

for(c in quant){
  print(paste0("Mean:",c,":",mean(auto[[c]])))
  print(paste0("SD:",c,":",sd(auto[[c]])))
  print(paste0("Range:", c,":",range(auto[[c]])))
  print("\n]")
}

#Removing 10th to 85th observation and finding mean/sd
auto.sub = auto[-10:-85,]
lapply(auto.sub,mean)
lapply(auto.sub,sd)
lapply(auto.sub, range)


#Relationship between various features of Auto dataset
pairs(auto)
pairs(~ mpg + displacement, auto)
pairs(~ mpg + horsepower, auto)
pairs(~ mpg + weight, auto)
pairs( ~mpg + acceleration, auto)
pairs(~ mpg + year, auto)
pairs( ~ cylinders + displacement, auto)

library(ggplot2)
ggplot(auto, aes(cylinders, displacement)) + geom_point() + xlab("Cylinders") + ylab("Displacement") + ggtitle("Auto: MPG vs Displacement")
ggplot(auto, aes(displacement, weight)) + geom_point(aes(color = "red", size = 2, alpha = 1/4)) + xlab("Cylinders") + ylab("Displacement") + ggtitle("Auto: MPG vs Displacement")
ggplot(auto, aes(displacement, horsepower)) + geom_point(shape = 21, color = "black" , fill = "white", stroke = 5) + xlab("Cylinders") + ylab("Displacement") + ggtitle("Auto: MPG vs Displacement")

#Can have color by categorical variable
ggplot(auto, aes(mpg, horsepower)) + geom_point(aes(color = factor(cylinders))) + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")
ggplot(auto, aes(mpg, weight)) + geom_point(aes(color = cylinders)) + scale_color_gradient(low = "blue") + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")
#Note we removed factor from cylinders

ggplot(auto, aes(mpg, horsepower)) + geom_point(aes(shape = factor(cylinders))) + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")
ggplot(auto, aes(mpg, horsepower)) + geom_point(aes(size = factor(cylinders))) + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")


ggplot(auto, aes(horsepower,weight)) + geom_point(aes(color = cylinders, shape = factor(origin))) + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")
ggplot(auto, aes(horsepower,weight)) + geom_point(aes(color = factor(cylinders), shape = factor(origin))) + xlab("MPG") + ylab("horsepower") + ggtitle("Auto: MPG vs Horsepower")


# Predict Mileage
#Mileage seems to be predictor; better predictor when combined with cylinders
ggplot(auto, aes(mpg,weight)) + geom_point(aes(color = factor(cylinders))) + xlab("MPG") + ylab("Weight") + ggtitle("Auto: MPG vs Weight")
```

```{r}

#Boston
library(MASS)
# (a) Read Data
names(Boston)

# (b) Pairwise correlation
pairs(Boston)

ggplot(Boston, aes(crim, dis)) + geom_point(aes(color = medv)) + xlab("Crime Rate") + ylab("Distance from Employment Center") + ggtitle("Boston: Crime rate vs Emp Center Distance")
ggplot(Boston, aes(nox, dis)) + geom_point(aes(color = factor(chas))) + xlab("Nitrogen Levels") + ylab("Employment Center distance") + ggtitle("Boston: Nitrogen vs Emp Center Distance")


#(c) Anything relevant to per capita crime rate
ggplot(Boston, aes(crim, dis)) + geom_point(aes(color = medv)) + xlab("Crime Rate") + ylab("Distance from Employment Center") + ggtitle("Boston: Crime rate vs Emp Center Distance")
#Distance to empl center seems to be relevant

# (d) Suburbs having high crime rates, tax rates, pupil-teacher ratio
#     1. High Crime rate
#         Stats of Boston Tax
          crim.mean = mean(Boston$crim)
          crim.sd = sd(Boston$crim)
          crim.limit = crim.mean + 2*crim.sd
         Boston[Boston$crim >=crim.limit,]
          
#        Another way: Look at range and pick up anumber
          range(Boston$crim)
#        Range is from 0 to 88 per capital crim rates.
          Boston[Boston$crim>50,]
#       Shows that 4 areas have per capita crime rate more than >50

#     2. High Tax Rate
        range(Boston$tax)
#       Stats of Boston Tax
        tax.Mean = mean(Boston$tax)
        tax.sd = sd(Boston$tax)
        limit = tax.mean + 2*tax.sd
      
      # Areas with more than 2 SD tax rates:
        Boston[Boston$tax>tax.sd,]

        
#     3. Student-Teacher
        
#       Stats of Boston Tax
        ptratio.mean = mean(Boston$ptratio)
        ptratio.sd = sd(Boston$ptratio)
        ptratio.2sd = ptratio.Mean + 2*ptratio.sd
      
        # Areas with more than 2 SD above mean pt ratio
        Boston[Boston$ptratio>ptratio.2sd,] #None above 2 SD  
        
        # Areas with more than 1.5 SD above mean pt ratio
        ptratio.1.5sd = ptratio.Mean + 1.5*ptratio.sd
        Boston[Boston$ptratio>ptratio.1.5sd,]
        

# (e) How many bound to Charles River
        dim(Boston[Boston$chas==1,])

        # 35 suburbs are bound to Charles river
        
# (f)
    median(Boston$ptratio)
    # Median Pupil Teacher ratio: 19.05
    
# (g)
    Boston[Boston$medv == min(Boston$medv),]
    summary(Boston)
    
    # Comparison of features of lowest value median of owner occupied home with other houses
    # For these suburbs
    # Crime rate is more than 2 SD higher
    # Zn: Proportion of lands zoned for lots of 25k = 0; True for atleast 50% of other suburbs
    # Indus: Proportion of non-retail business acre is at 18% which is in 3rd quartile
    # Nox levels are higher than median
    # Number of rooms are lower
    # Maximum number of hourse are built before 1940
    # Nearer to ekployment centers
    # Taxes are higher
    # Pupil-Teacher ratio is smaller
    # Higher % of african-americans
    # Higher % of lower stat population
    # Low median valueof owner occupied homes
    
    
# (h)
    dim(Boston[Boston$rm>7,]) #64 suburbs with >7 rooms
    dim(Boston[Boston$rm>8,]) #13 subuers with >8 rooms
    
    Boston[Boston$rm>8,]
    # Quick comments on suburbs with >8 rm
    # Crime rates are lower
    # Close to median distance to emp center
    # Median nox levels
    # Age varies
    # distance to emp center around median
    # Tax rate is lower
    # near median pt-ratio
    # Black around median
    # lower % of lower stat population
    # Higher median value

```
